// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onboarding.Tool.Data;

#nullable disable

namespace Onboarding.Tool.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702133425_AddTemplateConfirmationFields")]
    partial class AddTemplateConfirmationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address3")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostCode1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PostCode2")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LettingsEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LettingsPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalesEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SalesPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.HasIndex("InstanceId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchBuildDistrict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllSectors")
                        .HasColumnType("bit");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "District")
                        .IsUnique();

                    b.ToTable("BranchBuildDistricts");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchBuildDistrictSector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Sector")
                        .IsUnique();

                    b.ToTable("BranchBuildDistrictSectors");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Setting", "Value", "BranchId")
                        .IsUnique();

                    b.ToTable("BranchSetting");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Type", "InstanceId")
                        .IsUnique();

                    b.ToTable("Image");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Instance", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("DirectMailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LetterheadConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TemplatesConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.InstanceSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Setting", "Value", "InstanceId")
                        .IsUnique();

                    b.ToTable("InstanceSettings");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.PortalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("PortalName", "InstanceId")
                        .IsUnique();

                    b.ToTable("PortalAccount");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstanceId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Username", "InstanceId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Branch", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Address", "Address")
                        .WithOne()
                        .HasForeignKey("Onboarding.Tool.Model.Data.Branch", "AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Onboarding.Tool.Model.Data.Instance", "Instance")
                        .WithMany("Branches")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchBuildDistrict", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Branch", "Branch")
                        .WithMany("Districts")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchBuildDistrictSector", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.BranchBuildDistrict", "District")
                        .WithMany("Sectors")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchSetting", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Branch", "Branch")
                        .WithMany("Settings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Image", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Instance", "Instance")
                        .WithMany("Images")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.InstanceSetting", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Instance", "Instance")
                        .WithMany("Settings")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.PortalAccount", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Instance", "Instance")
                        .WithMany("PortalAccounts")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Users", b =>
                {
                    b.HasOne("Onboarding.Tool.Model.Data.Instance", "Instance")
                        .WithMany("Users")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Branch", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.BranchBuildDistrict", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("Onboarding.Tool.Model.Data.Instance", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Images");

                    b.Navigation("PortalAccounts");

                    b.Navigation("Settings");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
